sudo: required
services:
  - docker

before_install:
  - docker build -t linneakawe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true linneakawe/docker-react npm run test

language: generic